name = "pilotagebw"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "STORAGE_KV"
id = "0dd4bdb5eaa345f190605693ea883e25"
